apiVersion: v1
kind: ConfigMap
metadata:
  name: test-configmap
data:
  param.1: "2"
  param.2: "ho ho ho"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: configmap-container
      image: busybox
      command: [ "/bin/sh", "-c", "echo $(PARAM_1) $(PARAM_2)" ]
      env:
        - name: PARAM_1
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: param.1
        - name: PARAM_2
          valueFrom:
            configMapKeyRef:
              name: test-configmap
              key: param.2
    - name: volume-configmap-container
      image: busybox
      command: [ "/bin/sh", "-c", "cat /etc/config/param.1" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: test-configmap
  restartPolicy: Never
